create table if not exists users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(512) NOT NULL,
  CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

create table if not exists items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(512) NOT NULL,
  available BOOLEAN NOT NULL,
  user_id BIGINT NOT NULL,
  CONSTRAINT fk_item_user FOREIGN KEY(user_id) REFERENCES users(id)
);

create table if not exists bookings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status VARCHAR(10) NOT NULL,
  item_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  start_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  end_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  CONSTRAINT fk_booking_item FOREIGN KEY(item_id) REFERENCES items(id),
  CONSTRAINT fk_booking_user FOREIGN KEY(user_id) REFERENCES users(id)
);

create table if not exists comments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  text VARCHAR NOT NULL,
  item_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  CONSTRAINT fk_comment_item FOREIGN KEY(item_id) REFERENCES items(id),
  CONSTRAINT fk_comment_user FOREIGN KEY(user_id) REFERENCES users(id)
);